### PR TITLE
Update ActionButton.java

### PR DESCRIPTION
**Pull request by uriel-frankel**
I put the button on a list that is part of pager, and if i click on the button and make swipe the button remains pressed. 
So on default make it normal again

### CODE REVIEW

**Comment by vbaidak** [comment]
We could rework it to as follows:

When user swypes on a pressed **Action Button** and leaves the view without taking the finger - change the state to **NORMAL**, but do not change the state if swype happens within the **Action Button**.

What do you think?

**Comment by uriel-frankel** [comment]
Sounds good, but what about default behavior?

**Comment by vbaidak** [comment]
Actually we do not care about case **default**, because in this case **onTouchEvent(MotionEvent)** returns _false_, which means that this touch event is not processed.

I think we need to make changes for the case **MotionEvent.ACTION_MOVE**, where we should check whether action is inside the button or not. This will cover the situation, which you described.

I have already a method **isPointInsideCircle(float pointX, float pointY)** in [branch 1.1.0](https://github.com/shell-software/fab/tree/1.1.0), which checks whether action happens inside the main circle. You can check it [here](https://github.com/shell-software/fab/blob/1.1.0/fab/src/main/java/com/software/shell/fab/ActionButton.java)

**Comment by uriel-frankel** [comment]
Another issue:

public boolean isHidden() {

 return getVisibility() == INVISIBLE;

}

should be:

public boolean isHidden() {

 return getVisibility() != VISIBLE;

 }

because there is gone

**Comment by vbaidak** [comment]
Not sure about this. 

As I see it **isHidden()** shows whether view's visibility is set to **INVISIBLE** rather than not **VISIBLE**
For other cases like **GONE** we could have **isGone()** method

Could you please tell me whether this affects you somehow?

Thank you

**Pull request closed without merging**
